/**
 * Google Sheets tab names and column headers (mirrors BUILD_SPEC §2 / Airtable schema).
 * Row 1 on each tab must match these headers exactly (see docs/runbooks/google-sheets-setup.md).
 */

export const SHEET_TABS = {
  matters: "Matters",
  notes: "Notes",
  tasks: "Tasks",
  documents: "Documents",
  legalElements: "Legal Elements",
  pmInbox: "PM Inbox",
  contacts: "Contacts",
  events: "Events",
  strategyPatterns: "Strategy Patterns",
  corrections: "Corrections",
  people: "People",
} as const;

export type SheetTabKey = keyof typeof SHEET_TABS;

/** Canonical header row for each tab (column A → N). */
export const TAB_HEADERS: Record<SheetTabKey, readonly string[]> = {
  matters: [
    "row_id",
    "matter_id",
    "title",
    "case_type",
    "country",
    "posture",
    "court",
    "judge",
    "status",
    "assigned_to",
    "next_deadline",
    "next_hearing",
    "summary",
    "created_at",
    "updated_at",
    "lifecycle_stage",
    "assessment_data",
  ],
  notes: ["row_id", "matter_id", "content", "author", "created_at", "type"],
  tasks: [
    "row_id",
    "matter_id",
    "description",
    "status",
    "priority",
    "due_date",
    "assigned_to",
    "is_filing_deadline",
    "created_from_agent",
  ],
  documents: [
    "row_id",
    "matter_id",
    "title",
    "category",
    "created_at",
    "uploaded_by",
    "ocr_status",
    "pii_tier",
    "file_type",
  ],
  legalElements: [
    "row_id",
    "matter_id",
    "element_name",
    "assessment",
    "key_gap",
    "next_action",
    "supporting_facts",
    "supporting_cases",
  ],
  pmInbox: [
    "row_id",
    "title",
    "matter_id",
    "agent",
    "what_tried",
    "what_needed",
    "options",
    "status",
    "resolution",
    "created_at",
    "resolved_at",
  ],
  contacts: [
    "row_id",
    "display_name",
    "role",
    "email",
    "phone",
    "organization",
    "notes",
    "linked_matters",
  ],
  events: [
    "row_id",
    "matter_id",
    "summary",
    "type",
    "date",
    "time",
    "description",
    "location",
    "calendar_synced",
    "google_calendar_id",
    "created_at",
  ],
  strategyPatterns: [
    "row_id",
    "fact_pattern",
    "fact_pattern_detail",
    "strategy_used",
    "outcome",
    "correction_note",
    "created_at",
  ],
  corrections: [
    "row_id",
    "agent",
    "matter_id",
    "original_output",
    "attorney_edit",
    "correction_type",
    "reason",
    "applied_to",
    "created_at",
  ],
  people: ["row_id", "name", "role", "email", "is_active"],
};

/** Seed spreadsheet template for copy/paste or API bootstrap. */
export const SEED_SPREADSHEET_TITLE = "AssociateOnDemand — Firm Data";
